export const TYPES = {
  
  MODAL: {
    ADD_POST: 'ADD POST MODAL'
  },
  VALIDATION: {
    FORM_ADD_POST: 'VALIDATION FORM ADD POST'
  },
  POSTING: {
    ADDING_POST: 'ADDING POSTS'
  },
  DELETING: {
    DELETING_POST: 'DELETING POST'
  }
};
